<?php
// module/Blog/view/user/user/index.phtml:

$title = 'My users';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('user', array('action' => 'add')); ?>">Add new user</a>
</p>

<table class="table">
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Email</th>
        <th>Created</th>
        <th>Modified</th>
        <th></th>
    </tr>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($user->firstname); ?></td>
            <td><?php echo $this->escapeHtml($user->lastname); ?></td>
            <td><?php echo $this->escapeHtml($user->email); ?></td>
            <td><?php echo $this->escapeHtml($user->created); ?></td>
            <td><?php echo $this->escapeHtml($user->modified); ?></td>
            <td>
                <a href="<?php echo $this->url('user',
                    array('action' => 'edit', 'id' => $user->id)); ?>" class="btn btn-info btn-xs"><i class="glyphicon glyphicon-pencil"></i></a>
                <a href="<?php echo $this->url('user',
                    array('action' => 'delete', 'id' => $user->id)); ?>" class="btn btn-danger btn-xs"><i class="glyphicon glyphicon-trash"></i></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<?php
$this->headScript()
    ->appendFile($this->basepath("js/user/index.js"));
?>